### ISSUE TITLE
Rename matrixOfEUCountries variable

### ISSUE THREAD

**Issue by sushchyk** [BogdanOros/TPPS#2]
https://github.com/BogdanOros/TPPS/blob/425c9523e7563e68d08223642f0a6bdf16cb17ee/lab2/src/main/java/io/boros/Simulation.java#L17

Я думаю, було б достатньо назвати цю змінну та функцію просто `matrixOfCountries`.

І тут теж:
https://github.com/BogdanOros/TPPS/blob/master/lab2/src/main/java/io/boros/CountryInfo.java#L14

**Comment by BogdanOros** [comment]
Renamed
