### ISSUE TITLE
Code duplicating

### ISSUE THREAD

**Issue by IanaKhitsko** [BogdanOros/TPPS#4]
https://github.com/BogdanOros/TPPS/blob/f33a4852a8dfee89020441fb727742715321559f/lab2/src/main/java/io/boros/CountryInfo.java#L32-L36

This block is repeated 4 times. Introduce a new method for it.

**Comment by BogdanOros** [comment]
We are checking different arguments,  each one has a unique message, DRY will make not more readable.
