### ISSUE TITLE
Repeated condition

### ISSUE THREAD

**Issue by IanaKhitsko** [BogdanOros/TPPS#5]
https://github.com/BogdanOros/TPPS/blob/f33a4852a8dfee89020441fb727742715321559f/lab2/src/main/java/io/boros/CountryInfo.java#L112

if (amountToTransport <= 0)
  return 0;

?

**Comment by IanaKhitsko** [comment]
Remove it here:

https://github.com/BogdanOros/TPPS/blob/088f925a674425cc01baf370c3242e215eec35da/lab2/src/main/java/io/boros/CountryInfo.java#L112-L114

Or here^

https://github.com/BogdanOros/TPPS/blob/088f925a674425cc01baf370c3242e215eec35da/lab2/src/main/java/io/boros/CountryInfo.java#L125

**Comment by BogdanOros** [comment]
Fixed
